/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "CapSense_CSD.h"
#include "CapSense_CSD_CSHL.h"
#include "CapSense_CSD_Pins.h"
#include "CapSense_CSD_TunerHelper.h"
#include "LCD.h"
#include "LED1.h"
#include "LED1_aliases.h"
#include "LED2.h"
#include "LED2_aliases.h"
#include "CapSense_CSD_IntClock.h"
#include "CapSense_CSD_CompCH0.h"
#include "CapSense_CSD_AMuxCH0.h"
#include "CapSense_CSD_IdacCH0.h"
#include "LCD_LCDPort.h"
#include "LCD_LCDPort_aliases.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "PSoC3_8051.h"

/*[]*/

